# Generated by Django 2.1.2 on 2018-10-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0020_auto_20181025_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perros_rescatados',
            name='estado',
            field=models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='', max_length=30),
        ),
    ]
