# Generated by Django 2.1.2 on 2018-10-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0022_auto_20181026_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perros_rescatados',
            name='estado',
            field=models.CharField(blank=True, choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='perros_rescatados',
            name='nombre_perro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='perros_rescatados',
            name='raza_predominante',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
